#!/bin/bash

#################################################################
# Generate toys from ROOT file inputs prepared by preptoyinput.sh
#################################################################

DATE="2025_09_31"
source config/user.config  ## Loads USER, LOC_DIR, and EOS_DIR
OUTDIR="${EOS_DIR}/raw_inputs/${DATE}"

# Adjust number of toys
NTOYS=100 # Minimum of 2. 100 takes about 15 minutes per category (bkg-only + signal injections)

# Do you want to generate toys from MC or Data or both?
TOYSOURCE='DataAndMC'

# Categories for which to generate toys
## Six essential "fit categories", run with more toys (>= 100)

# ## Lep and Had with full Run2, gg0lV generated by-year and Run2
#declare -a CATSRUN2=('LepLo' 'LepHiT' 'HadXHi' 'HadXLo' 'VjjHi400' 'VjjTLo' 'VBFjjHiPtHi' 'VBFjjHiPtLo')
declare -a CATSYEAR=('gg0lVHi' 'gg0lVLo')

declare -a CATSRUN2=()
#declare -a CATSYEAR=()

# ## "Basic" categories to compare with 5 above, can run with fewer toys (<= 20)
# declare -a CATS=('LepHi' 'LepIncl' 'gg0lHi' 'gg0lLo' 'gg0lIncl' 'VBFjjHi' 'VBFjjLo' 'VBFjjIncl' 'VjjHi' 'VjjLo' 'VjjIncl' 'tt0lIncl')
# ## Alternate lepton categories for sensitivity optimization, can run with fewer toys (<= 20)
# declare -a CATS=('LepHiA' 'LepHiB' 'LepHiC' 'LepHiD' 'LepHiE' 'LepHiF' 'LepHiG' 'LepHiH' 'LepLoA' 'LepLoB' 'LepLoC' 'LepLoD' 'LepLoE' 'LepLoF' 'LepLoG' 'LepLoH')

## Generate toys for each category
for CAT in "${CATSRUN2[@]}"; do
    echo " > Making Run2 toys for $CAT category .. "
    echo "python3 Haa4b_makeMCtoy.py $CAT $NTOYS $TOYSOURCE Run2 >& makeMCtoy_${CAT}_${NTOYS}_${TOYSOURCE}_Run2.txt &"
    python3 Haa4b_makeMCtoy.py $CAT $NTOYS $TOYSOURCE Run2 >& makeMCtoy_${CAT}_${NTOYS}_${TOYSOURCE}_Run2.txt &
done

for CAT in "${CATSYEAR[@]}"; do
    for YEAR in Run2 2018 2017 2016; do
	echo " > Making $YEAR toys for $CAT category .. "
	echo "python3 Haa4b_makeMCtoy.py $CAT $NTOYS $TOYSOURCE $YEAR >& makeMCtoy_${CAT}_${NTOYS}_${TOYSOURCE}_${YEAR}.txt &"
	python3 Haa4b_makeMCtoy.py $CAT $NTOYS $TOYSOURCE $YEAR >& makeMCtoy_${CAT}_${NTOYS}_${TOYSOURCE}_${YEAR}.txt &
    done
done

top
