## From https://github.com/bouchamaouihichem/2DAlphabet/blob/master/Haa4b_fitsummary.py

import os
import sys
import numpy as np
import ROOT as R

R.gROOT.SetBatch(True)
import glob
R.gStyle.SetOptStat(0)  ## Don't display stat boxes

USER_IN = False # If True, use toy fits generated by user.  If False, use pre-existing inputs.
VERBOSE = False
#YEAR    = 'Run2'
YEAR    = sys.argv[4]
DATE    = '2025_09_31'
DMC     = str(sys.argv[1])  ## Data or MC
doSigInj = bool(int(sys.argv[2]))
sigconv = "BkgOnly"
if doSigInj:
  sigconv = "SigInj"
SIGINJ  = '*_mA_*_sigBr_*' if doSigInj  else ''
#CATS    = ['LepHiT']
CATS    = [sys.argv[3]]
MASSESA = ['12']+[str(iMA*5) for iMA in range(3,13)]
#FITS    = ['1x1C','2s2C']
FITS    = ['2s2C']
MIN_PTS = 100  ## Minimum number of points the scan should contain

if USER_IN:
    eos_from_config = [eos for eos in (open('config/user.config','r')).readlines() if eos.startswith('EOS_DIR=')]
    loc_from_config = [loc for loc in (open('config/user.config','r')).readlines() if loc.startswith('LOC_DIR=')]
    EOS_DIR = eos_from_config[0].replace('EOS_DIR=','').replace('\n','')
    LOC_DIR = loc_from_config[0].replace('LOC_DIR=','').replace('\n','')
    IN_DIR  = EOS_DIR+'/ToyStudies/'+DATE
    RND_DIR = LOC_DIR+'/output/%stoys/Mergecards/%s%srounded/%s' % (DMC, DMC, DMC, DATE)
    OUT_DIR = LOC_DIR+'/figures/MultiDimFit/'+DATE+'/'+YEAR
else:
    EOS_DIR = '/eos/cms/store/user/abrinke1/HiggsToAA/2DAlphabet'
    LOC_DIR = '/afs/cern.ch/work/a/abrinke1/public/HiggsToAA/2DAlphabet/CMSSW_11_3_4/src/2DAlphabet'
    IN_DIR  = EOS_DIR+'/ToyStudies/'+DATE
    RND_DIR = LOC_DIR+'/output/%stoys/Mergecards/%s%srounded/%s' % (DMC, DMC, DMC, DATE)
    OUT_DIR = './figures/MultiDimFit/'+DATE+'/'+YEAR

if not os.path.exists(OUT_DIR):
    os.system('mkdir -p '+OUT_DIR)

def solve_parab(pts,xs,ys):
    x1,x2,x3 = pts[0][xs],pts[1][xs],pts[2][xs]
    y1,y2,y3 = pts[0][ys],pts[1][ys],pts[2][ys]
    denom = (x1-x2)*(x1-x3)*(x2-x3)
    A     = (x3*(y2-y1) + x2*(y1-y3) + x1*(y3-y2)) / denom
    B     = (x3*x3*(y1-y2) + x2*x2*(y3-y1) + x1*x1*(y2-y3)) / denom
    C     = (x2*x3*(x2-x3)*y1+x3*x1*(x3-x1)*y2+x1*x2*(x1-x2)*y3) / denom
    return [A,B,C]

def get_parab_min(ABC):
    A,B,C = ABC
    x_min = -B/(2*A)
    y_min = A*pow(x_min,2) + B*x_min + C
    return [x_min, y_min]

# Global storage
best_fit_medians = {}
fit_categories = []

# File pattern for toy fit diagnostics
for cat in CATS:
    for mA in MASSESA:
        key = f"{cat}_{mA}"
        best_fit_medians[key] = {}

        for fit in FITS:
            #if (cat.startswith('Lep') != fit.startswith('1')): continue
            algo = 'MultiDimFit'
            base = 'higgsCombine.test'+algo
            suff = 'MultiDimFit.mH120.root'
            file_pattern = '%s/%s/%s/%s.%s.mA_%s.%s%s.%stoy*.%s' % (IN_DIR, cat, YEAR, base, cat, mA, fit, SIGINJ, DMC, suff)
            rnd_pattern  = '%s/%s/%s/%s.%s.mA_%s.%s%s.%s%srounded.%s' % (RND_DIR, cat, YEAR, base, cat, mA, fit, SIGINJ, DMC, DMC, suff)
            in_files  = glob.glob(file_pattern)
            rnd_files = glob.glob(rnd_pattern)
            if doSigInj:
                in_files  = [inf for inf in in_files]
                rnd_files = [rnf for rnf in rnd_files]
            else:
                in_files  = [inf for inf in in_files if not ('mA_%s_sigBr_' % mA) in inf]
                rnd_files = [rnf for rnf in rnd_files if not ('mA_%s_sigBr_' % rnf) in rnf]
            print('\nFound %d files matching pattern:' % len(in_files))
            print(file_pattern)
            print('Found %d files matching pattern:' % len(rnd_files))
            print(rnd_pattern)
            assert len(rnd_files) <= 1, '\nFound %d rounded files instead of 1!!! Quitting.\n' % len(rnd_files)
            found_round = (len(rnd_files) == 1)

            injSig = 0
            if doSigInj:
                injSig = float(in_files[0].split('_sigBr_')[1][0:3])*0.001

            fit_keys = [('r',float), ('rErr',float), ('NLL',float), ('NLLerr',float), ('pull',float), ('pullErr',float)]
            bst_pt = np.array([], dtype=fit_keys)
            zro_pt = np.array([], dtype=fit_keys)
            inj_pt = np.array([], dtype=fit_keys)

            iFile,nFiles,nEntry = 0,0,0
            for fName in rnd_files+in_files:
                iFile += 1
                if (iFile % int(np.sqrt(len(rnd_files+in_files)))) == 1:
                    print('Looking at file #%d / %d' % (iFile, len(rnd_files+in_files)))
                if not os.path.isfile(fName):
                    continue
                in_file = R.TFile.Open(fName)
                if not in_file or in_file.IsZombie(): continue
                in_tree = in_file.Get("limit")
                if not in_tree:
                    in_file.Close()
                    continue

                val_keys = [('r',float), ('dNLL',float), ('NLL',float), ('pull',float)]
                val = np.array([], val_keys)
                iEntry = 0
                for entry in in_tree:
                    iEntry += 1
                    nEntry += 1
                    val = np.append(val, np.array([(entry.r, entry.deltaNLL, -999., -999.)], dtype=val.dtype))
                if iEntry < MIN_PTS: 
                    in_file.Close()
                    continue

                if val[0]['r'] > 0.00001 or val[1]['r'] < 0.00001:
                    val = val[1:]
                rCut = 0.0002 if int(mA) <= 20 else (0.0005 if int(mA) <= 40 else 0.001)
                if val[0]['r'] > 5*rCut+0.00001: 
                    in_file.Close()
                    continue

                sort_dNLL = np.sort(val, order='dNLL')
                min_dNLL = sort_dNLL[0]['dNLL']
                sort_dNLL[:]['NLL'] = sort_dNLL[:]['dNLL'] - min_dNLL
                sort_dNLL[:]['pull'] = np.sqrt(2*sort_dNLL[:]['NLL'])

                parab_min = sort_dNLL[0:7]
                min_NLL_pt = [0.0, parab_min[0]['NLL']] if parab_min[0]['r'] < 0.00001 else get_parab_min(solve_parab([parab_min[i] for i in [0,1,2]], 'r', 'NLL'))
                sort_dNLL[:]['NLL']  = sort_dNLL[:]['NLL'] - min_NLL_pt[1]
                #sort_dNLL[:]['pull'] = np.sqrt(2*sort_dNLL[:]['NLL'])
                # clip this since cant have negative under sqrt
                sort_dNLL[:]['pull'] = np.sqrt(np.maximum(0, 2 * sort_dNLL[:]['NLL']))

                sort_r = np.sort(sort_dNLL, order='r')
                if sort_r[0]['r'] > 5*rCut+0.00001:
                    in_file.Close()
                    continue
                ## Find point corresponding to injected signal
                iInj = -99
                for iI in range(1, len(sort_r)-1):
                    if sort_r[iI-1]['r'] < injSig and sort_r[iI+1]['r'] > injSig:
                        iInj = iI

                bst_pt = np.append(bst_pt, np.array([(min_NLL_pt[0], 0, 0, 0, 0, 0)], dtype=fit_keys))
                if sort_r[0]['r'] < 0.00001:
                    zro_pt = np.append(zro_pt, np.array([(0, 0, sort_r[0]['NLL'], 0, np.sqrt(2*sort_r[0]['NLL']), 0)], dtype=fit_keys))
                else:
                    zro_NLL = solve_parab([sort_r[i] for i in [0,1,2]], 'r', 'NLL')[2]
                    zro_pt = np.append(zro_pt, np.array([(0, 0, zro_NLL, 0, np.sqrt(2*zro_NLL), 0)], dtype=fit_keys))

                if injSig > 0 and iInj >= 0:
                    inj_r   = sort_r[iInj]['r']
                    inj_NLL = sort_r[iInj]['NLL']
                    inj_pull = np.sqrt(2*inj_NLL)*(-1 if inj_r > min_NLL_pt[0] else 1)
                    if abs(inj_r - injSig) > 0.01 or abs(inj_r - injSig) / injSig > 0.20:
                        print('\nFile %d injected signal = %.1f%%, but closest point is %.1f%%. Skipping.' % (nFiles, injSig*100, inj_r*100))
                    else:
                        inj_pt = np.append(inj_pt, np.array([(inj_r, 0, inj_NLL, 0, inj_pull, 0)], dtype=fit_keys))

                nFiles += 1
                in_file.Close()

            h_str = 'h_MultiDim_%s_%s_%s_%s_%s_%s' % (cat, mA, fit, 'bkgOnly', DMC, YEAR)
            ipMax = 4.0
            h_inj_pull = R.TH1F(h_str+'_mu_inj_pull', h_str+'_mu_inj_pull', int(round(ipMax*20)), -1*ipMax, ipMax)

            for ii in range(len(inj_pt)):
              h_inj_pull.Fill(min(max(inj_pt[ii]['pull'], -1*(ipMax-0.0001)), ipMax-0.0001))

            # compute quantiles for median + sigma bands and ssave them for later
            p_hist = np.array([0.025,0.16,0.50,0.84,0.975])
            q_hist = np.array([0.,0.,0.,0.,0.])
            h_inj_pull.GetQuantiles(len(p_hist), q_hist, p_hist)
            q025,q16,q50,q84,q975 = q_hist
            if h_inj_pull.GetEntries() > 0:
                best_fit_medians[key][fit] = {
                    'median': q50,
                    'qdn1': q16,
                    'qup1': q84,
                    'qdn2': q025,
                    'qup2': q975
                }
                if fit not in fit_categories:
                    fit_categories.append(fit)

# Create and plot the median best-fit vs mA graph
def plot_best_fit_vs_mA(medians_dict, fits_list, output_dir, year, dmc):
    can_mA = R.TCanvas("median_best_fit_mA", "Median fit pull vs m_{A}", 800, 600)
    can_mA.cd()

    ma_values = sorted([int(key.split('_')[1]) for key in medians_dict.keys()])

    graphs, bands1, bands2 = {}, {}, {}

    # overlay fits for now (ggH can have multiple fits), then try to overlay BkgOnly and SigInj later
    for fit in fits_list:
        graphs[fit] = R.TGraph()
        graphs[fit].SetLineColor(R.kBlack)
        graphs[fit].SetMarkerColor(R.kBlack)
        graphs[fit].SetLineStyle(2)
        graphs[fit].SetMarkerStyle(20)
        graphs[fit].SetLineWidth(2)

        bands1[fit] = R.TGraphAsymmErrors()
        bands1[fit].SetFillColor(R.kGreen)
        bands1[fit].SetLineWidth(0)

        bands2[fit] = R.TGraphAsymmErrors()
        bands2[fit].SetFillColor(R.kYellow)
        bands2[fit].SetLineWidth(0)
     
    # Fill graphs + bands
    for ma in ma_values:
        for fit in fits_list:
            if CATS:
                key = f"{CATS[0]}_{ma}"
                if key in medians_dict and fit in medians_dict[key]:
                    fit_info = medians_dict[key][fit]
                    if isinstance(fit_info, dict):
                        median = fit_info['median']
                        qdn1, qup1 = fit_info['qdn1'], fit_info['qup1']
                        qdn2, qup2 = fit_info['qdn2'], fit_info['qup2']
                        n = graphs[fit].GetN()
                        graphs[fit].SetPoint(n, ma, median)

                        # 1 sigma band
                        bands1[fit].SetPoint(n, ma, median)
                        bands1[fit].SetPointError(n, 0, 0, median - qdn1, qup1 - median)

                        # 2 sigma band
                        bands2[fit].SetPoint(n, ma, median)
                        bands2[fit].SetPointError(n, 0, 0, median - qdn2, qup2 - median)
                    else:
                        n = graphs[fit].GetN()
                        graphs[fit].SetPoint(n, ma, fit_info)
    
    # Draw frame since Tgraphs don't like it when I set axis and range
    frame = R.TH1F("frame", ";m(A) [GeV];r",
                   100, min(ma_values) - 1, max(ma_values) + 1)
    frame.SetTitle(f"Pull vs Pseudoscalar Mass;m_{{A}} [GeV]; Best-fit branching fraction")
    frame.SetMinimum(-3.0)
    frame.SetMaximum(5.0)
    #frame.Draw("AXIS")
    frame.Draw("SAME")

    # Draw everything on top of the frame
    leg = R.TLegend(0.4, 0.72, 0.88, 0.88)
    leg.SetBorderSize(0)
    #leg.SetNColumns(2)
    for fit in sorted(fits_list):
        if graphs[fit].GetN() > 0:
            # comment out 2 sigma for now
            #bands2[fit].Draw("3 same")
            bands1[fit].Draw("3 same")
            graphs[fit].Draw("PL same")
            leg.AddEntry(graphs[fit], "Median fit pull", "lpe")

    leg.AddEntry(bands1[fits_list[0]], "68% interval of fit pulls", "f")
    # comment out 2 sigma for now
    #leg.AddEntry(bands2[fits_list[0]], "fit pulls #pm 2 std. deviation", "f")
    leg.Draw()

    # CMS stuff
    if YEAR == "Run2":
      lumi = "  138"
    elif YEAR == "2018":
      lumi = "59.83"
    elif YEAR == "2017":
      lumi = "41.48"
    else:# 2016
      lumi = "36.33"
    tex_string = "#bf{CMS} #it{Work in Progress}                                           " + lumi + " fb^{-1} (13 TeV)"
    tex = R.TLatex(0.5,0.9, tex_string)
    tex.SetNDC()
    tex.SetTextFont(42)
    tex.SetTextSize(0.04)
    tex.SetTextAlign(20)
    tex.Draw("SAME")
    
    # specify signal injected or not 
    if doSigInj:
      if DMC == "Data":
            sig = R.TLatex(0.18,0.67, "Toys from smoothed data with signal injected")
      else:
            sig = R.TLatex(0.18,0.67, "Toys from MC with signal injected")
    else:
      if DMC == "Data":
            sig = R.TLatex(0.18,0.67,"Toys from smoothed data")
      else:
            sig = R.TLatex(0.18,0.67,"Toys from background-only MC")

    sig.SetNDC()
    sig.SetTextFont(42)
    sig.SetTextSize(0.035)
    sig.Draw("SAME")
    
    catyr_string = "#bf{" + cat + ", " + YEAR + "}"
    catyr = R.TLatex(0.18,0.8, catyr_string)
    catyr.SetNDC()
    catyr.SetTextFont(42)
    catyr.SetTextSize(0.035)
    catyr.Draw("SAME")

    # Redraw axis
    #R.gPad.RedrawAxis() 

    # Define a horizontal line at y = 0.1
    if doSigInj:
      y_val1 = 0.0
      line1 = R.TLine(11, y_val1, 61, y_val1)
      line1.SetLineColor(R.kBlue)
      line1.SetLineStyle(3)
      line1.SetLineWidth(1)
      line1.Draw("same")

      y_val2 = -1.0
      line2 = R.TLine(11, y_val2, 61, y_val2)
      line2.SetLineColor(R.kRed)   
      line2.SetLineStyle(3)          
      line2.SetLineWidth(1)         
      line2.Draw("same")

      y_val3 = 1.0
      line3 = R.TLine(11, y_val3, 61, y_val3)
      line3.SetLineColor(R.kRed)   
      line3.SetLineStyle(3)          
      line3.SetLineWidth(1)         
      line3.Draw("same")

    can_mA.SaveAs(f"{output_dir}/pull_vs_mA_{cat}_{YEAR}_{dmc}_{sigconv}.png")
    can_mA.SaveAs(f"{output_dir}/pull_vs_mA_{cat}_{YEAR}_{dmc}_{sigconv}.pdf")
    graphs.clear(); bands1.clear() 
    # comment out 2 sigma for now
    #bands2.clear()
    del can_mA

# Call plotting
plot_best_fit_vs_mA(best_fit_medians, fit_categories, OUT_DIR, YEAR, DMC)

