## Script to plot goodness-of-fit (GoF) values from toys

import os
import sys
import numpy as np
import ROOT as R

R.gROOT.SetBatch(True)
import glob
R.gStyle.SetOptStat(0)  ## Don't display stat boxes

USER_IN = False  ## If True, use toy fits generated by user.  If False, use pre-existing inputs.
VERBOSE = False
YEAR    = 'Run2'
DATE    = '2025_09_31'
DMC     = str(sys.argv[1])  ## Data or MC
#CATS    = ['LepHiT','LepLo','gg0lVHi','gg0lVLo','HadXHi','HadXLo']
CATS    = ['VBFjjHiPtHi']
FITS    = ['1x1C']
MIN_TOYS = 90  ## Minimum number of toys the GoF test should contain
MAX_ITOY = 100  ## Maximum toy index to consider (for latest studies)

if USER_IN:
    eos_from_config = [eos for eos in (open('config/user.config','r')).readlines() if eos.startswith('EOS_DIR=')]
    loc_from_config = [loc for loc in (open('config/user.config','r')).readlines() if loc.startswith('LOC_DIR=')]
    EOS_DIR = eos_from_config[0].replace('EOS_DIR=','').replace('\n','')
    LOC_DIR = loc_from_config[0].replace('LOC_DIR=','').replace('\n','')
    IN_DIR  = EOS_DIR+'/ToyStudies/'+DATE
    #RND_DIR = LOC_DIR+'/output/%s/%stoys/Mergecards/%s%srounded' % (DATE, DMC, DMC, DMC)
    RND_DIR = LOC_DIR+'/output/%s/%stoys/Mergecards/%s%s' % (DATE, DMC, DMC, DMC)
    OUT_DIR = LOC_DIR+'/figures/GoF/'+DATE+'/'+YEAR
else:
    EOS_DIR = '/eos/cms/store/user/abrinke1/HiggsToAA/2DAlphabet'
    LOC_DIR = '/afs/cern.ch/work/a/abrinke1/public/HiggsToAA/2DAlphabet/CMSSW_11_3_4/src/2DAlphabet'
    IN_DIR  = EOS_DIR+'/ToyStudies/'+DATE
    #RND_DIR = LOC_DIR+'/output/%s/%stoys/Mergecards/%s%srounded' % (DATE, DMC, DMC, DMC)
    RND_DIR = LOC_DIR+'/output/%s/%stoys/Mergecards/%s%s' % (DATE, DMC, DMC, DMC)
    OUT_DIR = './figures/GoF/'+DATE+'/'+YEAR
## End conditional: if USER_IN / else


if not os.path.exists(OUT_DIR):
    os.system('mkdir -p '+OUT_DIR)

hsts = {}
# File pattern for toy fit diagnostics
for cat in CATS:
    hsts[cat] = {}
    for mA in ['12']:
        for fit in FITS:
            #if (cat.startswith('Lep') != fit.startswith('1')): continue
            algo = 'GoodnessOfFit'
            base = 'higgsCombine.test'+algo
            suff = algo+'.mH120.root'
            file_pattern = '%s/%s/%s/%s.%s.mA_%s.%s.%stoy*.%s' % (IN_DIR, cat, YEAR, base, cat, mA, fit, DMC, suff)
            #rnd_pattern  = '%s/%s/%s/%s.%s.mA_%s.%s.%s%srounded.%s' % (RND_DIR, cat, YEAR, base, cat, mA, fit, DMC, DMC, suff)
            rnd_pattern  = '%s/%s/%s/%s.%s.mA_%s.%s.%s%s.%s' % (RND_DIR, cat, YEAR, base, cat, mA, fit, DMC, DMC, suff)
            in_files_orig = glob.glob(file_pattern)
            in_files = [inf for inf in in_files_orig if int(inf.split('toy')[1].split('.')[0]) <= MAX_ITOY]
            rnd_files = glob.glob(rnd_pattern)
            print('\nFound %d files matching pattern:' % len(in_files))
            print(file_pattern)
            print('Found %d files matching pattern:' % len(rnd_files))
            print(rnd_pattern)
            assert len(rnd_files) <= 1, '\nFound %d rounded files instead of 1!!! Quitting.\n' % len(rnd_files)
            found_round = (len(rnd_files) == 1)

            h_str = 'h_GoF_quant_%s_%s_%s_%s' % (cat, fit, DMC, YEAR)
            hst = R.TH1F(h_str, h_str, 102, -0.01, 1.01)
            rnd_quant = -99

            iFile,nFiles,nEntry = 0,0,0
            for fName in rnd_files+in_files:
                fNameToy = fName.replace('.root','.123456.root')
                iFile += 1
                if (iFile % int(np.sqrt(len(rnd_files+in_files)))) == 1:
                    print('Looking at file #%d / %d' % (iFile, len(rnd_files+in_files)))
                if not os.path.isfile(fName):
                    print('\nWEIRD ERROR! %s does not exist!' % fName)
                    continue
                if not os.path.isfile(fNameToy):
                    print('\nTOY ERROR! %s does not exist!' % fNameToy)
                    continue
                in_file = None
                in_file_toy = None
                try:
                    in_file = R.TFile.Open(fName)
                except:
                    print('\nWEIRD ERROR! %s cannot be opened!' % fName)
                    continue
                try:
                    in_file_toy = R.TFile.Open(fNameToy)
                except:
                    print('\nWEIRD ERROR! %s cannot be opened!' % fNameToy)
                    continue
                if not in_file:
                    print('\nWEIRD ERROR! %s opened but somehow not there!' % fName)
                    continue
                if not in_file_toy:
                    print('\nWEIRD ERROR! %s opened but somehow not there!' % fNameToy)
                    continue
                if in_file.IsZombie():
                    print('\nWEIRD ERROR! %s is a zombie!' % fName)
                    continue
                if in_file_toy.IsZombie():
                    print('\nWEIRD ERROR! %s is a zombie!' % fNameToy)
                    continue
                in_tree = in_file.Get("limit")
                if not in_tree:
                    print('\nWEIRD ERROR! No "limit" tree in file %s' % fName)
                    in_file.Close()
                    in_file_toy.Close()
                    continue
                in_tree_toy = in_file_toy.Get("limit")
                if not in_tree_toy:
                    print('\nWEIRD ERROR! No "limit" tree in file %s' % fNameToy)
                    in_file.Close()
                    in_file_toy.Close()
                    continue
                val_keys = [('limit',float), ('iToy',int)]
                val = np.array([], val_keys)
                has_obs = False
                for entry in in_tree:
                    assert (not has_obs), '\nWEIRD ERROR! two observed values in file %s' % fNameToy
                    assert (entry.iToy == 0), '\nWEIRD ERROR! iToy = %d in file %s' % (entry.iToy, fNameToy)
                    has_obs = True
                    nEntry += 1
                    val = np.append(val, np.array([(entry.limit, entry.iToy)], dtype=val.dtype))
                if not has_obs:
                    print('\nERROR!!! File %d has no observed GoF metric! Skipping.' % iFile)
                    print(fName)
                    continue
                if VERBOSE:
                    print('\nSuccessfully running over:')
                    print(fName)
                    print(fNameToy)

                iEntry = 0
                for entry in in_tree_toy:
                    assert (entry.iToy > 0), '\nWEIRD ERROR! iToy = %d in file %s' % (entry.iToy, fNameToy)
                    iEntry += 1
                    val = np.append(val, np.array([(entry.limit, entry.iToy)], dtype=val.dtype))
                ## End loop: for entry in in_tree
                if iEntry < MIN_TOYS:
                    print('\nERROR!!! File %d has only %d toys! Skipping.' % (iFile, iEntry))
                    print(fNameToy)
                    continue

                sort_iToy = np.sort(val, order='iToy')
                obs_GoF = sort_iToy[0]['limit']
                exp_GoF = sort_iToy[1:]['limit']
                assert len(exp_GoF) == iEntry, '\nFound %d expected GoF values instead of %d!!! Quitting.\n' % (len(exp_GoF), iEntry)
                nBelow = np.count_nonzero(exp_GoF < obs_GoF)
                print('%s toy #%s: observed GoF = %.1f, %.1f%% of expected GoFs are lower' % (cat, fName.split('toy')[1][0:2], obs_GoF, 100*nBelow/len(exp_GoF)))
                nFiles += 1
                hst.Fill(max(-0.001, min(1.001, 1.0*nBelow/len(exp_GoF))))
                if found_round and fName == rnd_files[0]:
                    rnd_quant = 1.0*nBelow/len(exp_GoF)
                in_file.Close()
                in_file_toy.Close()
                
            ## End loop: for fName in rnd_files+in_files

            ## Find median
            ph = np.array([0.16,0.50,0.84])
            qh = np.array([0.,0.,0.])
            hst.GetQuantiles(3, qh, ph)
            qhdn = qh[0]
            qhmd = qh[1]
            qhup = qh[2]
            del ph,qh

            print('\nFinished loop for %s %s %s: %d / %d files actually used (%d entries)\n\n' % (cat, mA, fit, nFiles, len(rnd_files+in_files), nEntry))
            print('Mean = %.3f, StdDev = %.3f out of %d entries' % (hst.GetMean(), hst.GetStdDev(), hst.Integral()))
            print('Median = %.3f, 68%% range = [%.3f, %.3f]' % (qhmd, qhdn, qhup))
            print('Quantile from rounded distribution = %.3f' % rnd_quant)
            sys.exit()

            injStr = 'sigBr_%03d' % (injSig*1000) if doSigInj else 'bkgOnly'
            h_str = 'h_GoF_%s_%s_%s_%s_%s_%s' % (cat, mA, fit, injStr, DMC, YEAR)
            xMax = 0.10 if int(mA) < 22 else (0.2 if int(mA) < 42 else 0.40)
            zpMax = 8.0 if doSigInj else 4.0
            ipMax = 4.0
            h_best_mu  = R.TH1F(h_str+'_best_fit_mu', h_str+'_best_fit_mu', 100, 0, xMax)
            h_zro_pull = R.TH1F(h_str+'_mu_zero_pull', h_str+'_mu_zero_pull', 40, 0, zpMax)
            h_inj_pull = R.TH1F(h_str+'_mu_inj_pull', h_str+'_mu_inj_pull', 80, -1*ipMax, ipMax)

            ## Fill histograms
            best_mu_rnd,zro_pull_rnd,inj_pull_rnd = -99,-99,-99
            for ii in range(max(len(bst_pt), max(len(zro_pt), len(inj_pt)))):
                ## Value from rounded templates should be first entry
                if found_round and ii == 0:
                    best_mu_rnd  = min(bst_pt[ii]['r'], xMax-0.0001)
                    zro_pull_rnd = min(zro_pt[ii]['pull'], zpMax-0.0001)
                    if doSigInj:
                        inj_pull_rnd = min(max(inj_pt[ii]['pull'], -1*(ipMax-0.0001)), ipMax-0.0001)
                else:
                    if ii < len(bst_pt): h_best_mu.Fill(min(bst_pt[ii]['r'], xMax-0.0001))
                    if ii < len(zro_pt): h_zro_pull.Fill(min(zro_pt[ii]['pull'], zpMax-0.0001))
                    if doSigInj and ii < len(inj_pt):
                        h_inj_pull.Fill(min(max(inj_pt[ii]['pull'], -1*(ipMax-0.0001)), ipMax-0.0001))

            ## Plot histograms
            hst_list = [h_best_mu, h_zro_pull]+([h_inj_pull] if doSigInj else [])
            for hst in hst_list:
                # Find median
                p = np.array([0.16,0.50,0.84])
                q = np.array([0.,0.,0.])
                hst.GetQuantiles(3, q, p)
                qdn = q[0]
                qmd = q[1]
                qup = q[2]
                nZero = hst.GetBinContent(1)
                nHist = hst.Integral()
                del p,q
                print('\n%s median = %.3f (%d/%d = 0)' % (hst.GetName(), qmd, nZero, nHist))

                can = R.TCanvas(hst.GetName(), hst.GetName(), 800, 600)
                can.cd()
                if hst.GetBinLowEdge(1) == 0:
                    hst.SetBinContent(1,0)  ## Zero out first bin for visualization
                hst.SetLineColor(R.kBlue)
                hst.SetLineWidth(2)
                hst_max = max([hst.GetBinContent(ii) for ii in range(2, hst.GetNbinsX()+1)])
                hst.GetYaxis().SetRangeUser(0, hst_max*1.5)
                hst.Draw("hist")

                ## Draw arrow representing median
                marr = R.TArrow(qmd, 0, qmd, hst_max, 1.0, '|>')
                marr.SetLineWidth(4)
                marr.SetLineColor(R.kGreen+1)
                marr.SetFillColor(R.kGreen+1)
                marr.Draw("same")

                ## Draw arrow representing values from rounded template
                val_rnd = -99
                if found_round:
                    val_rnd = (best_mu_rnd if 'best_fit_mu' in hst.GetName() else
                               (zro_pull_rnd if 'mu_zero_pull' in hst.GetName() else
                                (inj_pull_rnd if 'mu_inj_pull' in hst.GetName() else -99)))
                    rarr = R.TArrow(val_rnd, 0, val_rnd, hst_max, 1.0, '|>')
                    rarr.SetLineWidth(4)
                    rarr.SetLineColor(R.kRed)
                    rarr.SetFillColor(R.kRed)
                    rarr.Draw("same")

                ## Annotate with median, fraction of fits with mu = 0
                vstr = ''
                if 'best_fit_mu' in hst.GetName():
                    vstr = 'best-fit #mu'
                elif 'mu_zero_pull' in hst.GetName():
                    vstr = '#mu = 0 pull'
                elif 'mu_inj_pull' in hst.GetName():
                    vstr = '#mu = %.1f%% pull' % (injSig*100)
                ltx1 = R.TLatex()
                ltx1.SetNDC()
                ltx1.SetTextSize(0.037)
                ltx1.SetTextColor(R.kGreen+2)
                ltx1.DrawLatex(0.13, 0.85, 'Median %s = %.3f [%.3f,%.3f]' % (vstr, qmd, qdn, qup))
                ltx2 = R.TLatex()
                ltx2.SetNDC()
                ltx2.SetTextSize(0.037)
                ltx2.SetTextColor(R.kBlue)
                if 'mu_inj_pull' in hst.GetName() or (doSigInj and 'mu_zero_pull' in hst.GetName()):
                    ltx2.DrawLatex(0.13, 0.77, '%d entries / %d files' % (nHist, len(in_files)))
                else:
                    ltx2.DrawLatex(0.13, 0.77, '%d / %d have %s = 0' % (nZero, nHist, vstr))
                ltx3 = R.TLatex()
                if found_round:
                    ltx3.SetNDC()
                    ltx3.SetTextSize(0.037)
                    ltx3.SetTextColor(R.kRed)
                    ltx3.DrawLatex(0.13, 0.69, 'Template %s = %.3f' % (vstr, val_rnd))
                leg = R.TLegend(0.58, 0.75, 0.88, 0.88)
                leg.AddEntry(hst, vstr+' values'+(' (> 0)' if not 'mu_inj_pull' in hst.GetName() else ''), 'l')
                leg.Draw()

                can.SaveAs(OUT_DIR+'/'+hst.GetName()+'.png')
                del leg,ltx3,ltx2,ltx1,can
            ## End loop: for hst in [h_best_mu, h_zro_pull]

        ## End loop: for fit in [
    ## End loop: for mA in [
## End loop: for cat in [
